language: node_js
node_js:
  - "6"
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
before_deploy:
  - rm -r node_modules
  - NODE_ENV=production npm install
  - sed -i 's/\/node_modules//g' .gitignore
  - git add node_modules/
deploy:
  edge: true
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id:
    secure: "lpVcbt1ceFMPghimFzS+5GXCd2yc4KH63inXNmgLxqpGO9Vt9IcTMcBQu4eaFacpg76nyrH+KOgK+GNMMY/jXDzly32pEnJXQgHI5TidQMuFpBft/ViN5NlKIg8Q4YV/3DWYWZnruCpQ3Anuh1ggPYojdx8MFiLB3GGrxBK01TtpakLRs40UHZgqWWEiGc1K52Qs1/LMaDs17FYjG2M+UTNji0zf4BONjaCRtJD94QufssgQYqPfeeJV1YdsrGnusZ3IRUiKFOZMuSH2axfKcc6ldaAitERo3w+lrM65OrIQbLethASOhj+HDtwX0O0MLmdMzLtF8LMREwlsUSDaz+4xllnfWxa0u+ZMrDVKIJJuQ90qdwpus/x21Zb9UR2J8Y/SbyLsvw876yumvquB9g819UDZ2YUcemDwy1tyBxDzmy6Ftn4ejl4xA3AmOtQXnppsBOYtwH4R1JyWZ+OybR0cL2OQKuVwkF+NXWZ83je1nyZ0ayefUXCpDobasv/AgSJZJjc06li8hmcsw/qYfQh5Ds79lFllwaSOcO0XiLjYs3HlwcMjF5t/Cul/feC2wpW/fMqkSPUglc0fNdRn4cVAiR8QTT8l+h65wMBUUucK+y5Uccg8Wxi0ilC0g4U6QwctHh1xQKKmbBchzV2L/qojbaMIa31xTcbSyu2ZqIY="
  secret-access-key:
    secure: "jMmDox+6ueDUNGNIbmq94GGJMdpZHpnk7vh/RLHGUy78ROqF0GdA1oR+XBKDpmknDcStf4b8sMhDNPeaQFao3EoDjmOdivq5h6bbGlaCP74Fvd0uDd2DFojpwW1GqgVkn4Of2m5BHA1bGg7yPnDy3cQHdPgF0lX4YhRzxN3/b99FiBIu1n4t7KYOT4cspB9uWWAEgryRA5/m1dN+iJCoLbGN4iONhUNoF6vgSA8IpuAWsnXiMemAdruFGf6xQRvhiaNxB/PFpguODxukLVrBG7rg7MUsZ0CE6M7veMgZxU750kyFjP8f2x+v3no5hrCmdQsy98KaGre0vw23jUhz5dj/nQ+TBpSiCnU0OBlc0Uie9zWRXotbBXOF7r1ASXTBpwOU22VldqgxquEn7Q9CLfqM5guLX9oK5R+R4u4wLlax5Qqn034186epbWeq8A2/KxFKJxfiVPR+/Jm09ydKl6BfqVUHC5fJ8ie+i7zvBWvaZpNXL+ftwlh9XQaHwis1KTc7wVZRFGeoRB7s3mECZQYPIlzn/i3aysKsmFhGOa7HffpE/pwR5QHcV8vyKH+K2aw+HSeN2Csx3KrbV1KJgmV4WXMmnl34VxApBevxdJF2mNQ+jiMWuX1JffbOsXuZKW37bdyxpQePNT+yx4ERBBuhh5xWf8JI/yd9ntUtr5Q="
  region: eu-west-1
  app: frontend-prototyping
  env: frontend-prototyping-beta-ricardo
  on:
    branch: master
