language: node_js
node_js:
  - "6"
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
before_deploy:
  - rm -r node_modules
  - NODE_ENV=production npm install
  - git add -f node_modules/
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $AWS_KEY_PLAIN
  secret-access-key: $AWS_TOKEN_PLAIN
  region: eu-west-1
  app: frontend-prototyping-beta-ricardo
  env: frontend-prototyping-beta-ricardo
  bucket_name: s3://elasticbeanstalk-eu-west-1-082666575234
  on:
    branch: master
