language: node_js
node_js:
  - "6"
env:
  - ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
before_deploy:
  - rm -r node_modules
  - NODE_ENV=production npm install
  - sed -i 's/\/node_modules//g' .gitignore
  - git add node_modules/
deploy:
  edge: true
  skip_cleanup: true
  provider: elasticbeanstalk
  access-key-id: $access-key-id
  secret-access-key: $security-token
  region: eu-west-1
  app: frontend-prototyping
  env: frontend-prototyping-beta-ricardo
  on:
    branch: master
