branch-defaults:
  master:
    environment: frontend-prototyping-beta-ricardo
global:
  application_name: frontend-prototyping
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: eu-west-1
  profile: null
  sc: git
